### ISSUE TITLE
Cannot install Telemetrydeck-React

### ISSUE THREAD

**Issue by Rheaparks** [typedigital/telemetrydeck-react#12]
### Preliminary Checks

- [X] This issue is not a duplicate.
- [X] The bug is reproducible.

### Description

Hello, 
I cannot install "telemetrydeck-react". 
By adding "npm install -S @typedigital/telemetrydeck-react"
I get this log : 

```
0 verbose cli /opt/homebrew/Cellar/node/21.1.0/bin/node /opt/homebrew/bin/npm
1 info using npm@10.2.0
2 info using node@v21.1.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/clementcardonnel/Downloads/test/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/clementcardonnel/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install @typedigital/telemetrydeck-react
22 verbose argv "install" "--save" "@typedigital/telemetrydeck-react"
23 timing npm:load:setTitle Completed in 2ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/clementcardonnel/.npm/_logs/2023-12-22T11_21_02_842Z-
26 verbose logfile /Users/clementcardonnel/.npm/_logs/2023-12-22T11_21_02_842Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 18ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 0ms
35 timing idealTree:init Completed in 5ms
36 timing idealTree:userRequests Completed in 2ms
37 silly idealTree buildDeps
38 silly fetch manifest @typedigital/telemetrydeck-react@*
39 http fetch GET 200 https://registry.npmjs.org/@typedigital%2ftelemetrydeck-react 1641ms (cache miss)
40 silly fetch manifest react@>= 16.8.0
41 http fetch GET 200 https://registry.npmjs.org/react 121ms (cache updated)
42 silly placeDep ROOT @typedigital/telemetrydeck-react@0.2.0-rc OK for: test@1.0.0 want: *
43 silly placeDep ROOT react@18.2.0 OK for: @typedigital/telemetrydeck-react@0.2.0-rc want: >= 16.8.0
44 silly fetch manifest @telemetrydeck/sdk@github:TelemetryDeck/JavaScriptSDK#pichfl/new-sdk
45 silly fetch manifest loose-envify@^1.1.0
46 http fetch GET 200 https://registry.npmjs.org/loose-envify 44ms (cache revalidated)
47 timing idealTree:#root Completed in 3099ms
48 silly placeDep node_modules/@typedigital/telemetrydeck-react @telemetrydeck/sdk@ OK for: @typedigital/telemetrydeck-react@0.2.0-rc want: github:TelemetryDeck/JavaScriptSDK#pichfl/new-sdk
49 timing idealTree:node_modules/@typedigital/telemetrydeck-react Completed in 1ms
50 silly placeDep ROOT loose-envify@1.4.0 OK for: react@18.2.0 want: ^1.1.0
51 silly fetch manifest js-tokens@^3.0.0 || ^4.0.0
52 http fetch GET 200 https://registry.npmjs.org/js-tokens 42ms (cache revalidated)
53 timing idealTree:node_modules/react Completed in 44ms
54 silly placeDep ROOT js-tokens@4.0.0 OK for: loose-envify@1.4.0 want: ^3.0.0 || ^4.0.0
55 timing idealTree:node_modules/loose-envify Completed in 1ms
56 timing idealTree:node_modules/js-tokens Completed in 0ms
57 timing idealTree:node_modules/@typedigital/telemetrydeck-react/node_modules/@telemetrydeck/sdk Completed in 0ms
58 timing idealTree:buildDeps Completed in 3146ms
59 timing idealTree:fixDepFlags Completed in 0ms
60 timing idealTree Completed in 3154ms
61 timing command:install Completed in 3159ms
62 verbose stack Error: The git reference could not be found
62 verbose stack     at makeError (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:26:13)
62 verbose stack     at /opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
62 verbose stack     at async /opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/git.js:268:19
62 verbose stack     at async withTempDir (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/fs/lib/with-temp-dir.js:21:14)
62 verbose stack     at async Promise.all (index 0)
62 verbose stack     at async #buildDepStep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1034:5)
62 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
62 verbose stack     at async Promise.all (index 1)
62 verbose stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
62 verbose stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:152:5)
63 verbose cwd /Users/clementcardonnel/Downloads/test
64 verbose Darwin 23.2.0
65 verbose node v21.1.0
66 verbose npm  v10.2.0
67 error code 1
68 error The git reference could not be found
69 error command git --no-replace-objects checkout pichfl/new-sdk
70 error error: pathspec 'pichfl/new-sdk' did not match any file(s) known to git
71 verbose exit 1
72 timing npm Completed in 3245ms
73 verbose unfinished npm timer reify 1703244062929
74 verbose unfinished npm timer reify:loadTrees 1703244062932
75 verbose code 1
76 error A complete log of this run can be found in: /Users/clementcardonnel/.npm/_logs/2023-12-22T11_21_02_842Z-debug-0.log
```

Thank you for your help

### Steps to Reproduce

1. Try to install with "npm install"
2.
3.
...

### Expected Result

Error :

```
npm ERR! code 1
npm ERR! The git reference could not be found
npm ERR! command git --no-replace-objects checkout pichfl/new-sdk
npm ERR! error: pathspec 'pichfl/new-sdk' did not match any file(s) known to git
```

### Actual Result

Error

### Environment

React (Browser)

### Framework

NextJS

### Version

14.0.1

**Comment by timidak** [comment]
Hi @Rheaparks, thank you for submitting this issue.
Unfortunately, the 0.2.0-rc depended on a release branch in the telemetrydeck-sdk repo.
With the new sdk released now, I'll publish a new version of the package and will come back to you. 🙂

**Comment by timidak** [comment]
Should be fixed now if you install it `@latest`.
